project:
  type: website
  output-dir: docs

website:
  title: "SDS Assignment"
  description: "Spatial Analysis of BBS Bird Data"

page-footer:
  left: "© 2026 Matěj Tvarůžka"
  right: "Built with Python & Quarto"
  
 # Navbar replaces the sidebar for a cleaner horizontal look
  navbar:
    background: primary
    search: true
    right:
      - text: "Portfolio"
        href: "https://matejtvar.github.io/"
      - icon: github
        href: "https://github.com/matejtvar/SDS-assignment"

  # Adds GitHub links to the top right
  repo-url: https://github.com/matejtvar/SDS-assignment
  repo-actions: [edit, issue]

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-location: right
    number-sections: true
    code-fold: false        # Hides code by default, very professional
    code-summary: "View Code"
    code-copy: true        # Adds a 'copy' button to code blocks
    code-tools: true       # Adds 'View Source' button at the top
    smooth-scroll: true
    anchor-sections: true  # Allows users to hover and link to headers