project:
  type: website
  output-dir: docs

website:
  title: "SDS Assignment"
  description: "Spatial Analysis of BBS Bird Data"
  
  # Indented correctly inside 'website'
  navbar:
    background: primary
    search: true
    right:
      - text: "Portfolio"
        href: "https://matejtvar.github.io/"
      - icon: github
        href: "https://github.com/matejtvar/SDS-assignment"

  # Indented correctly inside 'website'
  page-footer:
    left: "© 2026 Matěj Tvarůžka"
    right: "Built with Python & Quarto"

  repo-url: https://github.com/matejtvar/SDS-assignment
  repo-actions: [edit, issue]

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    # This makes the page wider (default is usually ~900px)
    grid:
      body-width: 1100px
      sidebar-width: 200px
      margin-width: 200px
    toc: true
    toc-location: right
    number-sections: true
    code-fold: true         # Change to 'true' to actually hide code
    code-summary: "View Code"
    code-copy: true
    code-tools: true
    smooth-scroll: true
    anchor-sections: true