project:
  type: website
  output-dir: docs

website:
  title: "SDS Assignment"
  description: "Spatial Analysis of BBS Bird Data"
  
  navbar:
    background: primary
    search: true
    right:
      - text: "Portfolio"
        href: "https://matejtvar.github.io/"
      - icon: github
        href: "https://github.com/matejtvar/SDS-assignment"

  page-footer:
    left: "© 2026 Matěj Tvarůžka"
    right: "Built with Python & Quarto"

  repo-url: https://github.com/matejtvar/SDS-assignment
  repo-actions: [edit, issue]

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    grid:
      body-width: 1100px
      sidebar-width: 200px
      margin-width: 200px
    toc: true
    toc-location: right
    number-sections: true
    code-fold: true
    code-summary: "View Code"
    code-tools:
      source: true
      toggle: true
      caption: "Code"
    smooth-scroll: true
    anchor-sections: true